### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by radex02**
I took the liberty of translating this nice addon to french.

### CODE REVIEW

**Comment by enen92** [comment]
Can you also contribute the strings in addon.xml? Thank you

**Comment by radex02** [comment]
Yes sure, here it is
```
<summary lang="fr_FR">Un économiseur d'écran comme Chromecast pour Kodi</summary>
<description lang="fr_FR">Affichez de jolies images provenant de l’écran de veille de Chromecast. Vous pouvez aussi afficher vos propres images avec leurs informations respectives.</description>
```

**Comment by enen92** [comment]
Please commit :)

**Comment by enen92** [comment]
Thanks :+1:

**Pull request merged**
