### PR TITLE
Update for Spanish language

### PR DESCRIPTION
**Pull request by roliverosc-zz**

### CODE REVIEW

**Comment by roliverosc-zz** [comment]
Correction of small details and elements after having to delete my fork.

**Review by enen92 — APPROVED** [review]

**Comment by enen92** [comment]
Thanks, i tried to translate the new ones myself but my spanish is crap :)

**Comment by roliverosc-zz** [comment]
I'll help you, don't worry. Thank you.

**Comment by enen92** [comment]
Actually I think there is a way to make the addon available in transifex for language teams to translate. I have to check how it is configured

**Pull request merged**
